services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "50000:8000"
      - "50001:9443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nicolas/config/portainer/data:/data
